# -*- coding: utf-8 -*-
"""
Created on Thu Mar  5 18:38:12 2020

@author: kpsr6
"""

# -*- coding: utf-8 -*-
"""Arimax.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJr_pX_QfNA0gREJPGWR1yi7kkI2SAxE
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np #imported numpy and Assigned as np
import pandas as pd #imported pandas and Assigned as pd
import statsmodels.api as sm
import pickle
from statsmodels.tsa.arima_model import ARIMAResults
import matplotlib.pyplot as plt #Used to plot the Graph by plt
# %matplotlib inline

#Used to Mount the Drive for Storage(kpsr6442GMAIL.COM(ML DATA))
#@from google.colab import drive
#@drive.mount('/content/drive')

##df=pd.read_csv('/content/drive/My Drive/ML DATA/train_sample3_1.csv')
df=pd.read_csv('/var/www/psk/html/machine-learning-deployment/MINI_22_6_20/data_set.csv')
#DATA SET OF CSV FORMAT
#READING THE CSV DATA SET

df
#THE END DATA OF DATA SET IS DISPLAYED
df.tail()

#df.drop(106,axis=0,inplace=True)

df.columns=['Month','Waiting List Conformed' ]
#CLASSIFING THE X AND Y AXIS.

df.head()
#THE TOP DATA OF DATA SET IS DISPLAYED

df['Month']=pd.to_datetime(df['Month'])
#THE MONTH COLUMN IN DATA SET IS TAKEN AS MONTH AND WHICH IS USED AS X AXIS ALSO.

df.head()

df.set_index('Month',inplace=True)
#MONTH VALUE IS VALID OR NULL IN THE ROW

df.head()

#@df.plot()
#PLOTING THE GRAPH by using X_axis and Y_axis as Month(X) && Waiting List Conformed(Y).

#Need to find order && Seasonal_order ,its a Proto-type Model Values
#Seasonal AutoRegressive Integrated Moving Average with exogenous regressors model
model=sm.tsa.statespace.SARIMAX(df['Waiting List Conformed'],order=(1, 0, 0),seasonal_order=(1,1,1,12))
results=model.fit()
#Best fitting model

#@#$$@#  pickle file

#start value is starting value to predict
#END Value is Ending value to predict.
df['forecast']=results.predict(start=90,end=106,dynamic=True)

from pandas.tseries.offsets import DateOffset
#days can be replaced with years,months,days etc.
#range is the range of values to predict in the graph.
future_dates=[df.index[-1]+ DateOffset(days=x)for x in range(0,15)]

future_datest_df=pd.DataFrame(index=future_dates[1:],columns=df.columns)

future_datest_df
#future values to be needed to predict

#combining past and future values   
future_df=pd.concat([df,future_datest_df])

b=future_df['forecast'] = results.predict(start = 105, end = 120, dynamic= True)
#future predicted values are saved in form of b.
#index value start and end in csv data set.dynamic true is no null values in between.
#@future_df[['Waiting List Conformed', 'forecast']].plot(figsize=(20, 8))
#print(pyplot.show())
#print(b)


#print(results.predict(start="2020-12-31"))
##  FOR PICKLE DATA FILE

pickle.dump(results, open('model.pkl','wb'))

#model = pickle.load(open('model.pkl','rb'))
